export const AuthTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    USER_PROFILE: "USER_PROFILE",
    IS_TEACHER: "IS_TEACHER"
};

export const EduTypes = {
    COURSES: "COURSES",
    USER_COURSES: "USER_COURSES",
    ADD_COURSE: "ADD_COURSE",
    REMOVE_COURSE: "REMOVE_COURSE",
    COURSE_LESSONS: "COURSE_LESSONS",
    COURSE_TEACHERS: "COURSE_TEACHERS",
    COURSE_HOMEWORK: "COURSE_HOMEWORK",
    HOMEWORK: "HOMEWORK",
    PROGRESS: "PROGRESS",
};